import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Layout/NavBar";
import Cursor from "@/components/UI/Cursor";
import DarkModeToggle from "@/components/UI/DarkModeToggle";
import { ThemeProviders } from "./providers";
import Footer from "@/components/Layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// from-[#300083] to-[#110A1C]
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} bg-white dark:bg-black  overflow-x-hidden `}
      >
        <ThemeProviders>
          <Cursor />
          <NavBar />
          {children}
          <Footer />
        </ThemeProviders>
      </body>
    </html>
  );
}
